### ISSUE TITLE
patch 1.11.2-0.0.0.0 doesn't like rpginventory 1.11.2-5.1.0.1

### ISSUE THREAD

**Issue by kreezxil** [ArtixAllMighty/Rpg-Inventory-2016#7]
And this is another reason the patch should simply compiled into the main mod.

Here are two screens when I started my client.

![desktop screenshot](https://user-images.githubusercontent.com/3880072/30111459-4c8c07f8-92d3-11e7-9a8f-31e59ff3b64b.png)

And this second screen is the proof that I have two files in my client

![desktop screenshot 1](https://user-images.githubusercontent.com/3880072/30111475-5f6127f0-92d3-11e7-8e61-e662d91df624.png)

**Comment by AbsolemJackdaw** [comment]
the problem being, i dont have the 1.11.2 code anymore.
i'll see what i can do.
have you tried loading it in WITHOUT twitch? because that should work just fine.

i have now uploaded the file as a secondary file to rpg inventory 1.11.2 (latest) on curseforge.
if that doesn't resolve the problem, i'll see if i can redecompile the code somehow and modify that

**Comment by kreezxil** [comment]
You can down port your 1.12 code and there are utilities out that can
rebuild the 1.11.2 recipes from json recipes if that is an issue.
